//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract_Position
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contract_Position()
        {
            this.Position_Forecast = new HashSet<Position_Forecast>();
            this.Workshares = new HashSet<Workshare>();
            this.Staff_Position = new HashSet<Staff_Position>();
        }
    
        public int ID { get; set; }
        public int Contract_ID { get; set; }
        public int Role_ID { get; set; }
        public int Contract_WBS_ID { get; set; }
        public short Position__ { get; set; }
        public short Info_Risk_ID { get; set; }
        public int LCAT_ID { get; set; }
        public Nullable<System.DateTime> DateNeeded { get; set; }
        public short Requisition_Status_ID { get; set; }
        public Nullable<short> Required_Security_Clearance_ID { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Contract_WB Contract_WBS { get; set; }
        public virtual Ref_Contract_LCAT Ref_Contract_LCAT { get; set; }
        public virtual Ref_Role Ref_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Position_Forecast> Position_Forecast { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Workshare> Workshares { get; set; }
        public virtual Adm_Info_Risk Adm_Info_Risk { get; set; }
        public virtual Adm_Security_Clearance Adm_Security_Clearance { get; set; }
        public virtual Adm_Requisition_Status Adm_Requisition_Status { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Position> Staff_Position { get; set; }
    }
}
