//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position_Forecast
    {
        public int ID { get; set; }
        public Nullable<int> Contract_Position_ID { get; set; }
        public Nullable<int> Pay_Period_ID { get; set; }
        public Nullable<decimal> FTE { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Contract_Position Contract_Position { get; set; }
        public virtual Ref_Pay_Period Ref_Pay_Period { get; set; }
    }
}
