//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Contract_LCAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Contract_LCAT()
        {
            this.Contract_Position = new HashSet<Contract_Position>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Contract_ID { get; set; }
        public Nullable<int> Vehicle_LCAT_ID { get; set; }
        public string ESF_LCAT { get; set; }
        public string Description { get; set; }
        public Nullable<short> Years_of_Experience_with_Degree { get; set; }
    
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Contract_Position> Contract_Position { get; set; }
        public virtual Ref_Contract_Vehicle_LCAT Ref_Contract_Vehicle_LCAT { get; set; }
    }
}
