//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Contract_Vehicle_LCAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ref_Contract_Vehicle_LCAT()
        {
            this.Ref_Contract_LCAT = new HashSet<Ref_Contract_LCAT>();
        }
    
        public int ID { get; set; }
        public short Contract_Vehicle_ID { get; set; }
        public string LCAT { get; set; }
        public string LCAT_Description { get; set; }
        public short Years_of_Experience_with_Degree { get; set; }
        public short Degree_ID { get; set; }
    
        public virtual Adm_Contract_Vehicle Adm_Contract_Vehicle { get; set; }
        public virtual Adm_Degree Adm_Degree { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ref_Contract_LCAT> Ref_Contract_LCAT { get; set; }
    }
}
