//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Clearance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff_Clearance()
        {
            this.Staff_Clearance_Workflow = new HashSet<Staff_Clearance_Workflow>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Staff_ID { get; set; }
        public Nullable<short> Security_Clearance_ID { get; set; }
        public Nullable<System.DateTime> Date_Authorized { get; set; }
        public Nullable<int> Contract_ID { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Contract Contract { get; set; }
        public virtual Staff Staff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Staff_Clearance_Workflow> Staff_Clearance_Workflow { get; set; }
        public virtual Adm_Security_Clearance Adm_Security_Clearance { get; set; }
    }
}
