//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Training
    {
        public int ID { get; set; }
        public int Staff_ID { get; set; }
        public int Training_ID { get; set; }
        public Nullable<System.DateTime> Date_Completed { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Staff Staff { get; set; }
        public virtual Ref_Training Ref_Training { get; set; }
    }
}
