//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff1
    {
        public int ID { get; set; }
        public int personKey { get; set; }
        public int companyID { get; set; }
        public string staffName { get; set; }
        public string suffix { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public string middleInitial { get; set; }
        public string alias { get; set; }
        public string location { get; set; }
        public string cellPhone { get; set; }
        public string personalCellPhone { get; set; }
        public string deskPhone { get; set; }
        public string companyEmail { get; set; }
        public bool isForeignNational { get; set; }
        public bool isBillable { get; set; }
        public int yearsOfExperience { get; set; }
        public System.DateTime hireDate { get; set; }
        public System.DateTime exitDate { get; set; }
        public string exitNote { get; set; }
        public int exitReasonID { get; set; }
        public bool isElligibleForRehire { get; set; }
        public System.DateTime createdOn { get; set; }
        public string createdBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string modifiedBy { get; set; }
    }
}
