//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff_Position
    {
        public int Staff_ID { get; set; }
        public int Contract_Position_ID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> Planned_Start_Date { get; set; }
        public Nullable<System.DateTime> Active_Start_Date { get; set; }
        public Nullable<System.DateTime> Active_End_Date { get; set; }
        public Nullable<int> Telework_Agreement_ID { get; set; }
        public Nullable<short> Resume_Status_ID { get; set; }
        public Nullable<bool> Is_Resume_Compliant { get; set; }
        public Nullable<bool> Is_LCAT_Compliant { get; set; }
        public string Compliance_Notes { get; set; }
        public string Email_Address { get; set; }
        public string Desk_Phone { get; set; }
        public string Cell_Phone { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Adm_Resume_Status Adm_Resume_Status { get; set; }
        public virtual Contract_Position Contract_Position { get; set; }
        public virtual Ref_Telework_Agreement Ref_Telework_Agreement { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
