//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workshare
    {
        public int ID { get; set; }
        public Nullable<int> Contract_Position_ID { get; set; }
        public Nullable<int> Company_ID { get; set; }
        public Nullable<System.DateTime> Date_Released { get; set; }
        public Nullable<bool> IsPrimary { get; set; }
        public System.DateTime Created_On { get; set; }
        public string Created_By { get; set; }
        public System.DateTime Modified_On { get; set; }
        public string Modified_By { get; set; }
    
        public virtual Contract_Position Contract_Position { get; set; }
        public virtual Ref_Company Ref_Company { get; set; }
    }
}
